### ISSUE TITLE
CurseForge启动器的导出问题

### ISSUE THREAD

**Issue by xiaxin113** [Yeah-Zero/Subtitle-Highlight#4]
希望可以把配置文件的名字改成subtitle_highlight.json，因为加入了这个模组后生成的配置文件名字是中文（字幕高亮.json），使用CurseForge启动器导出整合包的时候如果有中文文件的话会出问题（启动器安装不了）

另外标识符翻译这个模组的配置文件能否也能改成ldentifier_translation.json

**Comment by Yeah-Zero** [comment]
https://github.com/Yeah-Zero/Subtitle-Highlight/releases/tag/6
已完成。
